name = "computer-store-frontend"
compatibility_date = "2024-01-01"

[env.production]
compatibility_date = "2024-01-01"

[[env.production.routes]]
pattern = "computer-store.bangachieu2.workers.dev"
zone_name = "bangachieu2.workers.dev" 