name = "pos-backend"
main = "server/src/worker.js"
compatibility_date = "2024-01-15"
account_id = "5b62d10947844251d23e0eac532531dd"

[[d1_databases]]
binding = "DB"
database_name = "pos-db"
database_id = "5299f7e8-c458-4db4-9866-124c392a6dd8" 