name = "pos-backend-modern"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "pos-backend-modern-prod"

[env.staging]
name = "pos-backend-modern-staging"

[[d1_databases]]
binding = "DB"
database_name = "pos-db"
database_id = "5299f7e8-c458-4db4-9866-124c392a6dd8"

[vars]
ENVIRONMENT = "production"
API_VERSION = "2.0.0"
CORS_ORIGINS = "https://pos-system-production-2025.pages.dev,http://localhost:3000"

# Secrets to be set via CLI:
# wrangler secret put JWT_SECRET
# wrangler secret put ADMIN_PASSWORD
# wrangler secret put DATABASE_ENCRYPTION_KEY