name = "pos-computer-store-backend"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "pos-computer-store"
database_id = "17e414f8-049b-40cf-94d5-3ed3de876ca8"